### ISSUE TITLE
Binding to C libs

### ISSUE THREAD

**Issue by Its-Kenta** [tonysparks/litac-lang#24]
Hello!

What’s the process/steps of creating bindings to a C libraries?

**Comment by tonysparks** [comment]
I haven't focused too much on it, but it is supported.

There is a very buggy hacked together [c2lita](https://github.com/tonysparks/c2litac) tool (which needs a lot of attention to be much more robust) which generates litac bindings to C declared types.

In general, use the `foreign` note to define litac bindings to C types - [here](https://github.com/tonysparks/litac-lang/blob/master/stdlib/std/regex/re/re.lita) is an example that includes a C file and `foreign` declared functions defined in the C file.  The `cFile` note will essentially copy the source file into the generated litac output.

[Here](https://github.com/tonysparks/litac-lang/blob/master/stdlib/std/http/libcurl/libcurl.lita) is another example which references a precompiled library.

I'll write up a more detailed explanation document soon.
