### ISSUE TITLE
macOS ARM64 not supported

### ISSUE THREAD

**Issue by Its-Kenta** [tonysparks/litac-lang#40]
Looks like TCC does not support aarch64 macOS:
`Libtcc only supports x86_64 on macOS!`

**Comment by Its-Kenta** [comment]
Looks like building this tinycc on aarch64 works?
https://github.com/TinyCC/tinycc

**Comment by tonysparks** [comment]
tinycc compiles for me, but the tests fail on my m1.  I'm thinking of just removing libtcc dependency entirely, it is only used as a default if no buildCmd is specified.  At any rate, I added a check to not use libtcc if it isn't available for defaults

**Comment by Its-Kenta** [comment]
> tinycc compiles for me, but the tests fail on my m1. I'm thinking of just removing libtcc dependency entirely, it is only used as a default if no buildCmd is specified. At any rate, I added a check to not use libtcc if it isn't available for defaults

Is this now pushed to the latest and ready for test?

EDIT: Just looked into the updates, but looks like it still fails to build?

when building `build_bootstrap.sh`:
```
3 warnings generated.
Successfully built bootstrap
kenta@studio-m2 litac-lang % ./build.sh
Environment variable: /Users/kenta/Repositories/litac-lang
Running bootstrapped litaC...
Could not open file '/stdlib/std/builtins.lita'
```

When building `build.sh`:
```
3 warnings generated.
Successfully built bootstrap
kenta@studio-m2 litac-lang % ./build.sh
Environment variable: /Users/kenta/Repositories/litac-lang
Running bootstrapped litaC...
Could not open file '/stdlib/std/builtins.lita'


unable to parse builtins.lita

Total errors: 2


Segment                        Time              %      Mem            #
====================================================================================
PARSING                        0.000036            8% 170960         45
TYPE_CHECKING                  0.000000            0% 0              0
CGEN                           0.000000            0% 0              0
CCOMPILE                       0.000000            0% 0              0

Total time:         0.000447
Total memory:       1025872
Total allocations:  540
Total source lines: 0

Running litaC inception!...
./build.sh: line 41: ./litac_mac: No such file or directory
```

**Comment by tonysparks** [comment]
Sorry, I updated the build script to error when the `LITAC_HOME` variable isn't set.  Looks like you can set the variable to `/Users/kenta/Repositories/litac-lang` to get to work.

**Comment by Its-Kenta** [comment]
Wouldn't it be easier to temporarily set it in the shell script so that the language builds fine and then have the user decide on the path later?

This now worked and built, but small suggestion:

1. Once everything is built, perhaps have the unnecessary files that were only needed for building the compiler be cleaned up and deleted?
2. litac_mac executable should probably be just named litac?

Those suggestions would help us be able to move the language freely for people who prefer to place the language in more favourable location within /usr/local etc..

I think this can be closed now as the problem is solved.
